# define __OS
__OS=unsupported
case $(uname) in
Darwin)
  export __OS=Darwin
  ;;
Linux)
  [[ -f /etc/fedora-release ]] && export __OS=Fedora
  ;;
esac
export __OS

case "$__OS" in
Darwin)
  if [ -d "/opt/homebrew" ]; then
    HOMEBREW_PREFIX="/opt/homebrew"  # Apple Silicon (M1, M2, M3)
  elif [ -d "/usr/local/Homebrew" ]; then
    HOMEBREW_PREFIX="/usr/local"  # Intel
  else
    echo "Homebrew not found."
  fi

  # Ensure PATH includes $HOMEBREW_PREFIX/bin and $HOMEBREW_PREFIX/sbin in /etc/profile
  grep -qF 'export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin:$PATH"' /etc/profile || { echo 'export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin:$PATH"' | sudo tee -a /etc/profile > /dev/null && source /etc/profile; }
  # Ensure LIBRARY_PATH includes $HOMEBREW_PREFIX/lib in /etc/profile
  grep -qF 'export LIBRARY_PATH="$HOMEBREW_PREFIX/lib:$LIBRARY_PATH"' /etc/profile || { echo 'export LIBRARY_PATH="$HOMEBREW_PREFIX/lib:$LIBRARY_PATH"' | sudo tee -a /etc/profile > /dev/null && source /etc/profile; }

  export HOMEBREW_CASK_OPTS=--no-quarantine
  export HOMEBREW_NO_ENV_HINTS=1

  eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"

  export BROWSER='open'

  unset HOMEBREW_PREFIX
  ;;
Fedora)
  export BROWSER='firefox'
  ;;
esac

ulimit -n 1024

# Colors
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced # dark
# export LSCOLORS=ExFxBxDxCxegedabagacad # light

# Editors
export EDITOR='nano'
export VISUAL='nano'
export PAGER='cat'

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Less
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
